exports['all'] = require('./all')
exports['class'] = require('./class')
exports['id'] = require('./id')
exports['matches'] = require('./matches')
exports['one'] = require('./one')
exports['tag'] = require('./')